# Notebook 4 - Patrol Optimizer

This notebook converts hotspot analytics into an enforcement action plan.

It combines:
- `priority_score`
- `risk_level`
- `trajectory`
- `anomaly_status`

into a single `patrol_priority` score, then generates:
- Top 20 Enforcement Zones
- Best Patrol Windows

This is the operational answer to the hackathon prompt: how AI-driven parking intelligence can enable targeted enforcement.

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler

## Load Inputs

In [2]:
hotspot_events = pd.read_csv("hotspot_clustered.csv")
cluster_stats = pd.read_csv("hotspot_cluster_stats.csv")
trajectory_df = pd.read_csv("trajectory_analysis.csv")
anomaly_df = pd.read_csv("anomaly_analysis.csv")

print(hotspot_events.shape)
print(cluster_stats.shape)
print(trajectory_df.shape)
print(anomaly_df.shape)

(240654, 34)
(506, 20)
(506, 4)
(506, 6)

## Build Patrol Priority

In [3]:
patrol_df = (
    cluster_stats
    .merge(
        trajectory_df,
        on="cluster_id",
        how="left"
    )
    .merge(
        anomaly_df,
        on="cluster_id",
        how="left"
    )
)

trajectory_base_map = {
    "Declining": 0.25,
    "Stable": 0.50,
    "Escalating": 1.00,
    "Insufficient History": 0.10,
}

anomaly_base_map = {
    "Normal": 0.40,
    "Abnormal Surge": 1.00,
    "Abnormal Drop": 0.20,
}

patrol_df["trajectory_base_score"] = (
    patrol_df["trajectory"]
    .map(trajectory_base_map)
    .fillna(0.25)
)

patrol_df["priority_norm"] = MinMaxScaler().fit_transform(
    patrol_df[["priority_score"]]
)

patrol_df["r2_filled"] = patrol_df["r2"].fillna(0)
patrol_df["trajectory_weight"] = (
    patrol_df["trajectory_base_score"]
    * (0.50 + 0.50 * patrol_df["r2_filled"])
)

patrol_df["anomaly_base_score"] = (
    patrol_df["anomaly_status"]
    .map(anomaly_base_map)
    .fillna(0.40)
)

patrol_df["surge_intensity"] = patrol_df["z_score"].clip(lower=0).fillna(0)
patrol_df["surge_intensity_norm"] = MinMaxScaler().fit_transform(
    patrol_df[["surge_intensity"]]
)

patrol_df["anomaly_weight"] = (
    0.60 * patrol_df["anomaly_base_score"]
    + 0.40 * patrol_df["surge_intensity_norm"]
)

patrol_df["patrol_priority"] = (
    0.50 * patrol_df["priority_norm"]
    + 0.30 * patrol_df["trajectory_weight"]
    + 0.20 * patrol_df["anomaly_weight"]
)

patrol_df[[
    "cluster_id",
    "priority_score",
    "priority_norm",
    "risk_level",
    "trajectory",
    "anomaly_status",
    "patrol_priority"
]].head()

,cluster_id,priority_score,priority_norm,risk_level,trajectory,anomaly_status,patrol_priority
0,0.0,0.377956,0.514532,Medium,Stable,Normal,0.380267
1,1.0,0.488038,0.702897,High,Escalating,Abnormal Surge,0.686695
2,2.0,0.614845,0.919881,Critical,Declining,Normal,0.584285
3,3.0,0.584005,0.867110,Critical,Declining,Normal,0.572742
4,4.0,0.490399,0.706937,High,Declining,Normal,0.466451

## Top 20 Enforcement Zones

In [4]:
top_enforcement_zones = (
    patrol_df[
        [
            "cluster_id",
            "top_station",
            "centroid_lat",
            "centroid_lon",
            "violations",
            "avg_severity",
            "active_months",
            "priority_score",
            "risk_level",
            "trajectory",
            "r2",
            "current_month",
            "z_score",
            "anomaly_status",
            "patrol_priority"
        ]
    ]
    .sort_values(
        "patrol_priority",
        ascending=False
    )
    .head(20)
    .reset_index(drop=True)
)

top_enforcement_zones

,cluster_id,top_station,centroid_lat,centroid_lon,violations,avg_severity,active_months,priority_score,risk_level,trajectory,r2,current_month,z_score,anomaly_status,patrol_priority
0,114.0,Mahadevapura,12.996312,77.668619,1537,3.797658,6,0.660232,Critical,Escalating,0.000336,486.0,1.676563,Abnormal Surge,0.834530
1,6.0,K.R. Pura,13.008441,77.695320,3356,2.640644,6,0.617709,Critical,Escalating,0.179653,1030.0,1.712017,Abnormal Surge,0.826436
2,187.0,Whitefield,12.951403,77.717501,349,4.272206,6,0.594333,Critical,Escalating,0.262344,177.0,1.863662,Abnormal Surge,0.824784
3,31.0,Malleshwaram,13.010297,77.553283,8563,1.635642,6,0.569432,Critical,Escalating,0.057540,2127.0,1.664340,Abnormal Surge,0.764946
4,248.0,Hulimavu,12.885738,77.641532,465,1.997849,6,0.509601,High,Escalating,0.155951,204.0,1.984256,Abnormal Surge,0.741056
5,39.0,HAL Old Airport,12.948252,77.699061,1542,3.484436,6,0.643953,Critical,Escalating,0.034360,399.0,0.936182,Normal,0.724689
6,54.0,Kodigehalli,13.047512,77.575880,866,1.764434,6,0.483510,High,Escalating,0.775036,266.0,1.352130,Normal,0.714822
7,422.0,K.S. Layout,12.911473,77.552080,35,4.457143,5,0.483789,High,Escalating,0.092048,21.0,1.831613,Abnormal Surge,0.703404
8,50.0,Banaswadi,12.993636,77.662697,760,1.436842,6,0.454326,High,Escalating,0.193301,320.0,1.786767,Abnormal Surge,0.691628
9,23.0,Mahadevapura,13.000354,77.676957,1623,2.723352,6,0.594344,Critical,Escalating,0.034651,462.0,1.132262,Normal,0.689974
10,1.0,Byatarayanapura,12.957341,77.518812,427,2.491803,6,0.488038,High,Escalating,0.010723,129.0,1.623759,Abnormal Surge,0.686695
11,24.0,Chikkajala,13.185452,77.680117,3899,2.126699,6,0.607067,Critical,Escalating,0.003797,978.0,0.861801,Normal,0.685631
12,56.0,Kodigehalli,13.071025,77.588392,5024,1.752389,6,0.571307,Critical,Escalating,0.126356,1330.0,1.155257,Normal,0.684921
13,20.0,Mahadevapura,12.995657,77.695559,1095,2.715982,6,0.569267,Critical,Escalating,0.049545,346.0,1.358980,Normal,0.679638
14,83.0,Bellandur,12.917465,77.672113,217,2.165899,6,0.442870,High,Escalating,0.110554,82.0,1.966233,Abnormal Surge,0.676448
15,100.0,Mahadevapura,12.979177,77.695127,426,3.338028,6,0.567917,Critical,Escalating,0.005657,134.0,1.429752,Normal,0.674674
16,71.0,Magadi Road,12.985537,77.549511,1050,2.203810,6,0.434729,High,Escalating,0.088120,372.0,1.742122,Abnormal Surge,0.657334
17,134.0,Hulimavu,12.876270,77.596035,453,1.463576,6,0.427132,Medium,Escalating,0.108968,176.0,1.510109,Abnormal Surge,0.644868
18,333.0,Mahadevapura,12.985498,77.708243,31,3.096774,5,0.384245,Medium,Escalating,0.352975,11.0,1.507836,Abnormal Surge,0.644688
19,343.0,Adugodi,12.940171,77.619963,54,2.444444,4,0.334864,Medium,Escalating,0.547486,31.0,1.750226,Abnormal Surge,0.641115

## Best Patrol Windows

## Dashboard Centerpiece

In [5]:
top_enforcement_zones[
    [
        "cluster_id",
        "top_station",
        "risk_level",
        "trajectory",
        "anomaly_status",
        "patrol_priority"
    ]
].head(20)

,cluster_id,top_station,risk_level,trajectory,anomaly_status,patrol_priority
0,114.0,Mahadevapura,Critical,Escalating,Abnormal Surge,0.834530
1,6.0,K.R. Pura,Critical,Escalating,Abnormal Surge,0.826436
2,187.0,Whitefield,Critical,Escalating,Abnormal Surge,0.824784
3,31.0,Malleshwaram,Critical,Escalating,Abnormal Surge,0.764946
4,248.0,Hulimavu,High,Escalating,Abnormal Surge,0.741056
5,39.0,HAL Old Airport,Critical,Escalating,Normal,0.724689
6,54.0,Kodigehalli,High,Escalating,Normal,0.714822
7,422.0,K.S. Layout,High,Escalating,Abnormal Surge,0.703404
8,50.0,Banaswadi,High,Escalating,Abnormal Surge,0.691628
9,23.0,Mahadevapura,Critical,Escalating,Normal,0.689974
10,1.0,Byatarayanapura,High,Escalating,Abnormal Surge,0.686695
11,24.0,Chikkajala,Critical,Escalating,Normal,0.685631
12,56.0,Kodigehalli,Critical,Escalating,Normal,0.684921
13,20.0,Mahadevapura,Critical,Escalating,Normal,0.679638
14,83.0,Bellandur,High,Escalating,Abnormal Surge,0.676448
15,100.0,Mahadevapura,Critical,Escalating,Normal,0.674674
16,71.0,Magadi Road,High,Escalating,Abnormal Surge,0.657334
17,134.0,Hulimavu,Medium,Escalating,Abnormal Surge,0.644868
18,333.0,Mahadevapura,Medium,Escalating,Abnormal Surge,0.644688
19,343.0,Adugodi,Medium,Escalating,Abnormal Surge,0.641115

In [6]:
day_order = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
]

top_cluster_ids = top_enforcement_zones["cluster_id"]

window_df = hotspot_events[
    hotspot_events["cluster_id"].isin(top_cluster_ids)
].copy()

window_df["day_of_week"] = pd.Categorical(
    window_df["day_of_week"],
    categories=day_order,
    ordered=True
)

window_df = window_df.dropna(subset=["hour", "day_of_week"]).copy()
window_df["hour"] = window_df["hour"].astype(int)

cluster_totals = (
    window_df
    .groupby("cluster_id")
    .agg(cluster_total_violations=("id", "count"))
    .reset_index()
)

window_profiles = (
    window_df
    .groupby(
        ["cluster_id", "day_of_week", "hour"],
        observed=True
    )
    .agg(
        window_violations=("id", "count"),
        avg_window_severity=("max_severity", "mean"),
        weekend_share=("is_weekend", "mean")
    )
    .reset_index()
    .merge(
        cluster_totals,
        on="cluster_id",
        how="left"
    )
)

window_profiles["hour_percentage"] = (
    window_profiles["window_violations"]
    / window_profiles["cluster_total_violations"]
)

window_profiles["window_violations_norm"] = MinMaxScaler().fit_transform(
    window_profiles[["window_violations"]]
)
window_profiles["avg_window_severity_norm"] = MinMaxScaler().fit_transform(
    window_profiles[["avg_window_severity"]]
)

window_profiles["window_score"] = (
    0.75 * window_profiles["window_violations_norm"]
    + 0.25 * window_profiles["avg_window_severity_norm"]
)

window_profiles["window_rank"] = (
    window_profiles
    .groupby("cluster_id")["window_score"]
    .rank(method="first", ascending=False)
)

window_profiles["patrol_window"] = (
    window_profiles["day_of_week"].astype(str)
    + " "
    + window_profiles["hour"].map(lambda x: f"{x:02d}:00-{(x + 1):02d}:00")
)

best_windows_detailed = (
    window_profiles
    .sort_values(
        ["cluster_id", "window_score"],
        ascending=[True, False]
    )
    .query("window_rank <= 3")
    .copy()
)
best_windows_detailed["hour_percentage_label"] = (
    (100 * best_windows_detailed["hour_percentage"])
    .round(1)
    .astype(str)
    + "% of hotspot activity"
)

best_windows_detailed.head(20)

,cluster_id,day_of_week,hour,window_violations,avg_window_severity,weekend_share,cluster_total_violations,hour_percentage,window_violations_norm,avg_window_severity_norm,window_score,window_rank,patrol_window,hour_percentage_label
31,1.0,Thursday,9,1,6.000000,0.0,427,0.002342,0.000000,0.833333,0.208333,1.0,Thursday 09:00-10:00,0.2% of hotspot activity
4,1.0,Monday,18,2,5.500000,0.0,427,0.004684,0.002959,0.750000,0.189719,2.0,Monday 18:00-19:00,0.5% of hotspot activity
43,1.0,Friday,9,9,5.000000,0.0,427,0.021077,0.023669,0.666667,0.184418,3.0,Friday 09:00-10:00,2.1% of hotspot activity
202,6.0,Sunday,18,152,3.085526,1.0,3356,0.045292,0.446746,0.347588,0.421956,1.0,Sunday 18:00-19:00,4.5% of hotspot activity
203,6.0,Sunday,19,144,2.645833,1.0,3356,0.042908,0.423077,0.274306,0.385884,2.0,Sunday 19:00-20:00,4.3% of hotspot activity
164,6.0,Friday,19,120,2.983333,0.0,3356,0.035757,0.352071,0.330556,0.346692,3.0,Friday 19:00-20:00,3.6% of hotspot activity
263,20.0,Sunday,5,143,2.678322,1.0,1095,0.130594,0.420118,0.279720,0.385019,1.0,Sunday 05:00-06:00,13.1% of hotspot activity
261,20.0,Sunday,3,120,3.833333,1.0,1095,0.109589,0.352071,0.472222,0.382109,2.0,Sunday 03:00-04:00,11.0% of hotspot activity
264,20.0,Sunday,6,148,2.250000,1.0,1095,0.135160,0.434911,0.208333,0.378267,3.0,Sunday 06:00-07:00,13.5% of hotspot activity
305,23.0,Thursday,2,57,5.298246,0.0,1623,0.035120,0.165680,0.716374,0.303354,1.0,Thursday 02:00-03:00,3.5% of hotspot activity
310,23.0,Thursday,19,51,4.529412,0.0,1623,0.031423,0.147929,0.588235,0.258006,2.0,Thursday 19:00-20:00,3.1% of hotspot activity
281,23.0,Tuesday,2,37,5.027027,0.0,1623,0.022797,0.106509,0.671171,0.247674,3.0,Tuesday 02:00-03:00,2.3% of hotspot activity
363,24.0,Monday,23,121,1.611570,0.0,3899,0.031034,0.355030,0.101928,0.291754,1.0,Monday 23:00-24:00,3.1% of hotspot activity
393,24.0,Wednesday,19,110,2.181818,0.0,3899,0.028212,0.322485,0.196970,0.291106,2.0,Wednesday 19:00-20:00,2.8% of hotspot activity
412,24.0,Thursday,22,123,1.422764,0.0,3899,0.031547,0.360947,0.070461,0.288325,3.0,Thursday 22:00-23:00,3.2% of hotspot activity
566,31.0,Sunday,4,339,1.719764,1.0,8563,0.039589,1.000000,0.119961,0.779990,1.0,Sunday 04:00-05:00,4.0% of hotspot activity
550,31.0,Saturday,5,249,1.602410,1.0,8563,0.029079,0.733728,0.100402,0.575396,2.0,Saturday 05:00-06:00,2.9% of hotspot activity
502,31.0,Wednesday,4,238,1.630252,0.0,8563,0.027794,0.701183,0.105042,0.552148,3.0,Wednesday 04:00-05:00,2.8% of hotspot activity
624,39.0,Thursday,22,92,4.467391,0.0,1542,0.059663,0.269231,0.577899,0.346398,1.0,Thursday 22:00-23:00,6.0% of hotspot activity
589,39.0,Monday,22,79,4.430380,0.0,1542,0.051232,0.230769,0.571730,0.316009,2.0,Monday 22:00-23:00,5.1% of hotspot activity

In [7]:
best_windows_summary = (
    best_windows_detailed
    .assign(
        patrol_window_summary=(
            best_windows_detailed["patrol_window"]
            + " ("
            + best_windows_detailed["hour_percentage_label"]
            + ")"
        )
    )
    .groupby("cluster_id")
    .agg(
        recommended_windows=(
            "patrol_window_summary",
            lambda x: " | ".join(x)
        )
    )
    .reset_index()
)

best_patrol_windows = (
    top_enforcement_zones
    .merge(
        best_windows_summary,
        on="cluster_id",
        how="left"
    )
    [[
        "cluster_id",
        "top_station",
        "risk_level",
        "trajectory",
        "anomaly_status",
        "patrol_priority",
        "recommended_windows"
    ]]
)

best_patrol_windows

,cluster_id,top_station,risk_level,trajectory,anomaly_status,patrol_priority,recommended_windows
0,114.0,Mahadevapura,Critical,Escalating,Abnormal Surge,0.834530,Friday 04:00-05:00 (4.6% of hotspot activity) ...
1,6.0,K.R. Pura,Critical,Escalating,Abnormal Surge,0.826436,Sunday 18:00-19:00 (4.5% of hotspot activity) ...
2,187.0,Whitefield,Critical,Escalating,Abnormal Surge,0.824784,Thursday 03:00-04:00 (14.0% of hotspot activit...
3,31.0,Malleshwaram,Critical,Escalating,Abnormal Surge,0.764946,Sunday 04:00-05:00 (4.0% of hotspot activity) ...
4,248.0,Hulimavu,High,Escalating,Abnormal Surge,0.741056,Sunday 20:00-21:00 (10.5% of hotspot activity)...
5,39.0,HAL Old Airport,Critical,Escalating,Normal,0.724689,Thursday 22:00-23:00 (6.0% of hotspot activity...
6,54.0,Kodigehalli,High,Escalating,Normal,0.714822,Wednesday 21:00-22:00 (6.5% of hotspot activit...
7,422.0,K.S. Layout,High,Escalating,Abnormal Surge,0.703404,Monday 20:00-21:00 (11.4% of hotspot activity)...
8,50.0,Banaswadi,High,Escalating,Abnormal Surge,0.691628,Monday 09:00-10:00 (5.9% of hotspot activity) ...
9,23.0,Mahadevapura,Critical,Escalating,Normal,0.689974,Thursday 02:00-03:00 (3.5% of hotspot activity...
10,1.0,Byatarayanapura,High,Escalating,Abnormal Surge,0.686695,Thursday 09:00-10:00 (0.2% of hotspot activity...
11,24.0,Chikkajala,Critical,Escalating,Normal,0.685631,Monday 23:00-24:00 (3.1% of hotspot activity) ...
12,56.0,Kodigehalli,Critical,Escalating,Normal,0.684921,Monday 06:00-07:00 (6.3% of hotspot activity) ...
13,20.0,Mahadevapura,Critical,Escalating,Normal,0.679638,Sunday 05:00-06:00 (13.1% of hotspot activity)...
14,83.0,Bellandur,High,Escalating,Abnormal Surge,0.676448,Saturday 05:00-06:00 (1.4% of hotspot activity...
15,100.0,Mahadevapura,Critical,Escalating,Normal,0.674674,Thursday 03:00-04:00 (6.6% of hotspot activity...
16,71.0,Magadi Road,High,Escalating,Abnormal Surge,0.657334,Saturday 20:00-21:00 (0.1% of hotspot activity...
17,134.0,Hulimavu,Medium,Escalating,Abnormal Surge,0.644868,Wednesday 00:00-01:00 (21.0% of hotspot activi...
18,333.0,Mahadevapura,Medium,Escalating,Abnormal Surge,0.644688,Wednesday 04:00-05:00 (6.5% of hotspot activit...
19,343.0,Adugodi,Medium,Escalating,Abnormal Surge,0.641115,Wednesday 20:00-21:00 (14.8% of hotspot activi...

## Final Enforcement Action Plan

In [8]:
patrol_action_plan = (
    top_enforcement_zones
    .merge(
        best_windows_summary,
        on="cluster_id",
        how="left"
    )
)

patrol_action_plan["deployment_level"] = pd.cut(
    patrol_action_plan["patrol_priority"],
    bins=[0, 0.4, 0.7, 1.0],
    labels=[
        "Routine Monitoring",
        "Targeted Patrol",
        "Immediate Enforcement"
    ],
    include_lowest=True
)

patrol_action_plan[[
    "cluster_id",
    "risk_level",
    "trajectory",
    "anomaly_status",
    "patrol_priority",
    "deployment_level",
    "recommended_windows"
]]

,cluster_id,risk_level,trajectory,anomaly_status,patrol_priority,deployment_level,recommended_windows
0,114.0,Critical,Escalating,Abnormal Surge,0.834530,Immediate Enforcement,Friday 04:00-05:00 (4.6% of hotspot activity) ...
1,6.0,Critical,Escalating,Abnormal Surge,0.826436,Immediate Enforcement,Sunday 18:00-19:00 (4.5% of hotspot activity) ...
2,187.0,Critical,Escalating,Abnormal Surge,0.824784,Immediate Enforcement,Thursday 03:00-04:00 (14.0% of hotspot activit...
3,31.0,Critical,Escalating,Abnormal Surge,0.764946,Immediate Enforcement,Sunday 04:00-05:00 (4.0% of hotspot activity) ...
4,248.0,High,Escalating,Abnormal Surge,0.741056,Immediate Enforcement,Sunday 20:00-21:00 (10.5% of hotspot activity)...
5,39.0,Critical,Escalating,Normal,0.724689,Immediate Enforcement,Thursday 22:00-23:00 (6.0% of hotspot activity...
6,54.0,High,Escalating,Normal,0.714822,Immediate Enforcement,Wednesday 21:00-22:00 (6.5% of hotspot activit...
7,422.0,High,Escalating,Abnormal Surge,0.703404,Immediate Enforcement,Monday 20:00-21:00 (11.4% of hotspot activity)...
8,50.0,High,Escalating,Abnormal Surge,0.691628,Targeted Patrol,Monday 09:00-10:00 (5.9% of hotspot activity) ...
9,23.0,Critical,Escalating,Normal,0.689974,Targeted Patrol,Thursday 02:00-03:00 (3.5% of hotspot activity...
10,1.0,High,Escalating,Abnormal Surge,0.686695,Targeted Patrol,Thursday 09:00-10:00 (0.2% of hotspot activity...
11,24.0,Critical,Escalating,Normal,0.685631,Targeted Patrol,Monday 23:00-24:00 (3.1% of hotspot activity) ...
12,56.0,Critical,Escalating,Normal,0.684921,Targeted Patrol,Monday 06:00-07:00 (6.3% of hotspot activity) ...
13,20.0,Critical,Escalating,Normal,0.679638,Targeted Patrol,Sunday 05:00-06:00 (13.1% of hotspot activity)...
14,83.0,High,Escalating,Abnormal Surge,0.676448,Targeted Patrol,Saturday 05:00-06:00 (1.4% of hotspot activity...
15,100.0,Critical,Escalating,Normal,0.674674,Targeted Patrol,Thursday 03:00-04:00 (6.6% of hotspot activity...
16,71.0,High,Escalating,Abnormal Surge,0.657334,Targeted Patrol,Saturday 20:00-21:00 (0.1% of hotspot activity...
17,134.0,Medium,Escalating,Abnormal Surge,0.644868,Targeted Patrol,Wednesday 00:00-01:00 (21.0% of hotspot activi...
18,333.0,Medium,Escalating,Abnormal Surge,0.644688,Targeted Patrol,Wednesday 04:00-05:00 (6.5% of hotspot activit...
19,343.0,Medium,Escalating,Abnormal Surge,0.641115,Targeted Patrol,Wednesday 20:00-21:00 (14.8% of hotspot activi...

## Save Outputs

In [9]:
top_enforcement_zones.to_csv(
    "top_enforcement_zones.csv",
    index=False
)

best_windows_detailed.to_csv(
    "best_patrol_windows_detailed.csv",
    index=False
)

best_patrol_windows.to_csv(
    "best_patrol_windows.csv",
    index=False
)

patrol_action_plan.to_csv(
    "patrol_action_plan.csv",
    index=False
)

print("Saved")

Saved

In [10]:
patrol_action_plan["deployment_level"].value_counts()

deployment_level
Targeted Patrol          12
Immediate Enforcement     8
Routine Monitoring        0
Name: count, dtype: int64

In [11]:
patrol_action_plan[
[
    "cluster_id",
    "risk_level",
    "trajectory",
    "anomaly_status",
    "patrol_priority",
    "deployment_level",
    "recommended_windows"
]
].head(20)

,cluster_id,risk_level,trajectory,anomaly_status,patrol_priority,deployment_level,recommended_windows
0,114.0,Critical,Escalating,Abnormal Surge,0.834530,Immediate Enforcement,Friday 04:00-05:00 (4.6% of hotspot activity) ...
1,6.0,Critical,Escalating,Abnormal Surge,0.826436,Immediate Enforcement,Sunday 18:00-19:00 (4.5% of hotspot activity) ...
2,187.0,Critical,Escalating,Abnormal Surge,0.824784,Immediate Enforcement,Thursday 03:00-04:00 (14.0% of hotspot activit...
3,31.0,Critical,Escalating,Abnormal Surge,0.764946,Immediate Enforcement,Sunday 04:00-05:00 (4.0% of hotspot activity) ...
4,248.0,High,Escalating,Abnormal Surge,0.741056,Immediate Enforcement,Sunday 20:00-21:00 (10.5% of hotspot activity)...
5,39.0,Critical,Escalating,Normal,0.724689,Immediate Enforcement,Thursday 22:00-23:00 (6.0% of hotspot activity...
6,54.0,High,Escalating,Normal,0.714822,Immediate Enforcement,Wednesday 21:00-22:00 (6.5% of hotspot activit...
7,422.0,High,Escalating,Abnormal Surge,0.703404,Immediate Enforcement,Monday 20:00-21:00 (11.4% of hotspot activity)...
8,50.0,High,Escalating,Abnormal Surge,0.691628,Targeted Patrol,Monday 09:00-10:00 (5.9% of hotspot activity) ...
9,23.0,Critical,Escalating,Normal,0.689974,Targeted Patrol,Thursday 02:00-03:00 (3.5% of hotspot activity...
10,1.0,High,Escalating,Abnormal Surge,0.686695,Targeted Patrol,Thursday 09:00-10:00 (0.2% of hotspot activity...
11,24.0,Critical,Escalating,Normal,0.685631,Targeted Patrol,Monday 23:00-24:00 (3.1% of hotspot activity) ...
12,56.0,Critical,Escalating,Normal,0.684921,Targeted Patrol,Monday 06:00-07:00 (6.3% of hotspot activity) ...
13,20.0,Critical,Escalating,Normal,0.679638,Targeted Patrol,Sunday 05:00-06:00 (13.1% of hotspot activity)...
14,83.0,High,Escalating,Abnormal Surge,0.676448,Targeted Patrol,Saturday 05:00-06:00 (1.4% of hotspot activity...
15,100.0,Critical,Escalating,Normal,0.674674,Targeted Patrol,Thursday 03:00-04:00 (6.6% of hotspot activity...
16,71.0,High,Escalating,Abnormal Surge,0.657334,Targeted Patrol,Saturday 20:00-21:00 (0.1% of hotspot activity...
17,134.0,Medium,Escalating,Abnormal Surge,0.644868,Targeted Patrol,Wednesday 00:00-01:00 (21.0% of hotspot activi...
18,333.0,Medium,Escalating,Abnormal Surge,0.644688,Targeted Patrol,Wednesday 04:00-05:00 (6.5% of hotspot activit...
19,343.0,Medium,Escalating,Abnormal Surge,0.641115,Targeted Patrol,Wednesday 20:00-21:00 (14.8% of hotspot activi...